/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.CustomerOrdersData;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.CustomerOrders;

/**
 *
 * @author Akash Bahri
 */
public class CustomerEmployeePanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerEmployeePanel
     */
    JPanel botpanel;
    JFrame loginframe;
    CustomerOrders selectedRequest;
    private ArrayList <CustomerOrders> orderlist;
    int loggedInID = -1;
    public CustomerEmployeePanel(JPanel botpanel, int loggedInID, JFrame loginframe) {
        this.botpanel = botpanel;
        this.loggedInID = loggedInID;
        this.loginframe = loginframe;
        populateTable();
        initComponents();
    }
    public void populateTable() {
        try {
            this.orderlist = CustomerOrdersData.getAllOrders();
            DefaultTableModel model = (DefaultTableModel) order_table.getModel();
            model.setRowCount(0);
            for (CustomerOrders Order :orderlist ) {
               Object[] row = new Object[9];
                row[0] =Order.getOrderId();
                row[1]=Order.getCreatorId();
                row[2]=Order.getProdName();
                row[3]=Order.getAddress();
                row[4]=Order.getDate();
                row[5]=Order.getAgentId();
                row[6]=Order.getStatus();
                row[7]=Order.getNotes();              
                model.addRow(row);
            }
            //clearFields();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewOrderButton = new javax.swing.JButton();
        orderTable = new javax.swing.JScrollPane();
        order_table = new javax.swing.JTable();
        UpdateButton = new javax.swing.JButton();
        AddressTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        Title_Label = new javax.swing.JLabel();

        NewOrderButton.setText("New Order");
        NewOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewOrderButtonActionPerformed(evt);
            }
        });

        order_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Order Id", "Order Creator Id", "Product Name", "Delivery Address", "Order Placed Date", "Delivery Agent Id", "Order Status", "Notes"
            }
        ));
        orderTable.setViewportView(order_table);

        UpdateButton.setText("Request Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Update Address");

        logoutButton.setBackground(new java.awt.Color(51, 0, 0));
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        Title_Label.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Title_Label.setForeground(new java.awt.Color(102, 102, 102));
        Title_Label.setText("ASSOCIATE PORTAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderTable))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NewOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(Title_Label)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Title_Label)
                .addGap(26, 26, 26)
                .addComponent(orderTable, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = order_table.getSelectedRow();
        if(selectedIndex == -1) {
            JOptionPane.showMessageDialog(this,"Please select a request to update", "Cannot update request", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        selectedRequest = orderlist.get(selectedIndex);
        String newAddress = AddressTextField.getText();
        CustomerOrdersData.NewUpdateRequest(selectedRequest,newAddress);
        
//        addressForUpdate=selectedRequest.getNewAddress();
//        orderid=selectedRequest.getOrderId();
//        System.out.println(orderid);
//        orderUpdate=new CustomerManager();
//         orderUpdate.setAddress(addressForUpdate);
//         orderUpdate.setOrderId(orderid);
//        CustomerManagerDBC.updateAddress(orderUpdate);
//        populateTable();
        
        
        
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void NewOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewOrderButtonActionPerformed
        // TODO add your handling code here:
        NewOrderForm form =  new NewOrderForm(botpanel,loggedInID,loginframe);
         botpanel.add(form);
        CardLayout lay = (CardLayout)botpanel.getLayout();
        lay.next(botpanel);
    }//GEN-LAST:event_NewOrderButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        LoginPanel lp = new LoginPanel(botpanel, loginframe);
         botpanel.add(lp);
        CardLayout lay = (CardLayout)botpanel.getLayout();
        lay.next(botpanel);
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JButton NewOrderButton;
    private javax.swing.JLabel Title_Label;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JScrollPane orderTable;
    private javax.swing.JTable order_table;
    // End of variables declaration//GEN-END:variables
}
