/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Akash Bahri
 */
public class LoginPanel extends javax.swing.JPanel {
  int c=0;
  int p=0;
  JPanel bottomPanel;
  int loggedInID=-5;
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(JPanel bottomPanel) {
        initComponents();
        this.bottomPanel = bottomPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_Label = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JTextField();
        LogInButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 76, 109));
        setMinimumSize(new java.awt.Dimension(943, 600));

        Title_Label.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Title_Label.setForeground(new java.awt.Color(255, 255, 255));
        Title_Label.setText("UPS DELIVERY SERVICES ");

        UsernameTextField.setText("USERNAME");
        UsernameTextField.setToolTipText("Username");
        UsernameTextField.setActionCommand("<Not Set>");
        UsernameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameTextFieldMouseClicked(evt);
            }
        });
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });
        UsernameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsernameTextFieldKeyPressed(evt);
            }
        });

        PasswordTextField.setText("PASSWORD");
        PasswordTextField.setToolTipText("Password");
        PasswordTextField.setActionCommand("<Not Set>");
        PasswordTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordTextFieldMouseClicked(evt);
            }
        });
        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });
        PasswordTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordTextFieldKeyPressed(evt);
            }
        });

        LogInButton.setBackground(new java.awt.Color(0, 153, 153));
        LogInButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LogInButton.setForeground(new java.awt.Color(255, 255, 255));
        LogInButton.setText("LOG IN");
        LogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Title_Label)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(UsernameTextField)
                            .addComponent(LogInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(328, 328, 328))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Title_Label)
                .addGap(48, 48, 48)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(LogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        UsernameTextField.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void UsernameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsernameTextFieldKeyPressed
        // TODO add your handling code here:
      
        if(0==c){
        UsernameTextField.setText("");
        c++;}
       
    }//GEN-LAST:event_UsernameTextFieldKeyPressed

    private void UsernameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameTextFieldMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_UsernameTextFieldMouseClicked

    private void PasswordTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldMouseClicked

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void PasswordTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordTextFieldKeyPressed
        // TODO add your handling code here:
         if(p==0){
        PasswordTextField.setText("");
        p++;}
       
    }//GEN-LAST:event_PasswordTextFieldKeyPressed

    private void LogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInButtonActionPerformed
        // TODO add your handling code here:
        String role="associate";
        String company="";
        switch(role){
                case "admin" -> {if(company.equalsIgnoreCase("UPS")) {
                //CREATE OBJECT FOR SPECIFIC PANEL
                }
                else if(company.equalsIgnoreCase("other")){
                //CREATE OBJECT FOR SPECIFIC PANEL
                }
                else {UPS_admin_MainFrame n = new UPS_admin_MainFrame();
        n.show();}}
                case "associate" -> {
                    {if(company.equalsIgnoreCase("UPS")) {
                //CREATE OBJECT FOR SPECIFIC PANEL
                }
                else if(company.equalsIgnoreCase("other")){
                //CREATE OBJECT FOR SPECIFIC PANEL
                }
                else{ OrderCancellationRequestPanel orp = new OrderCancellationRequestPanel();
//        LoginPanel l = new LoginPanel(bottomPanel);
        CustomerEmployeePanel emp = new CustomerEmployeePanel(bottomPanel,loggedInID);
        bottomPanel.add(emp);
        CardLayout lay = (CardLayout)bottomPanel.getLayout();
        lay.next(bottomPanel);}}
          }
                default -> {
                   
        
          }
        }
    }//GEN-LAST:event_LogInButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogInButton;
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JLabel Title_Label;
    private javax.swing.JTextField UsernameTextField;
    // End of variables declaration//GEN-END:variables
}
