/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.CustomerOrdersData;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.CustomerOrders;




/**
 *
 * @author Akash Bahri
 */
public class NewOrderForm extends javax.swing.JPanel {
CustomerOrders selectedRequest;
    private ArrayList <CustomerOrders> orderlist;
    /**
     * Creates new form NewOrderForm
     */
    int loggedInID =-1;
    JPanel botpanel;
    JFrame loginframe;
    public NewOrderForm(JPanel botpanel, int loggedInID, JFrame loginframe) {
        initComponents();     
        this.loginframe = loginframe;
        this.botpanel=botpanel;
        this.loggedInID = loggedInID;
         CreatorIdText.setText(""+loggedInID);
        CreatorIdText.setEditable(false);
        StatusText.setText("pending_assignment");
        StatusText.setEditable(false);
        
        AgentText.setText("Not Assigned yet");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        OrderIdText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CreatorIdText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ProductText = new javax.swing.JTextField();
        AddressText = new javax.swing.JTextField();
        AgentText = new javax.swing.JTextField();
        DateText = new javax.swing.JTextField();
        StatusText = new javax.swing.JTextField();
        NotesText = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        Title_Label = new javax.swing.JLabel();

        jLabel1.setText("Order ID");

        OrderIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderIdTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Order Creator ID");

        CreatorIdText.setBackground(new java.awt.Color(204, 204, 204));
        CreatorIdText.setEnabled(false);

        jLabel3.setText("Product Name");

        jLabel4.setText("Delivery Address");

        jLabel5.setText("Delivery Agent ID");

        jLabel6.setText("Order Status");

        jLabel7.setText("Notes");

        jLabel8.setText("Order Placed Date");

        AgentText.setBackground(new java.awt.Color(204, 204, 204));
        AgentText.setEnabled(false);

        SubmitButton.setBackground(new java.awt.Color(0, 76, 109));
        SubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton.setText("SUBMIT");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        Title_Label.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Title_Label.setForeground(new java.awt.Color(102, 102, 102));
        Title_Label.setText("NEW ORDER FORM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SubmitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(OrderIdText)
                                    .addComponent(CreatorIdText)
                                    .addComponent(AddressText)
                                    .addComponent(ProductText)
                                    .addComponent(DateText)
                                    .addComponent(AgentText)
                                    .addComponent(StatusText)
                                    .addComponent(NotesText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(Title_Label)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Title_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(OrderIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CreatorIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ProductText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(AddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(DateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AgentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(StatusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NotesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OrderIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderIdTextActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
       CustomerEmployeePanel cust = new CustomerEmployeePanel(botpanel,loggedInID,loginframe);
        botpanel.add(cust);
        CardLayout lay = (CardLayout)botpanel.getLayout();
        lay.next(botpanel);
        CustomerOrders neworder = new CustomerOrders();
        neworder.setOrderId(Integer.parseInt(OrderIdText.getText()));
        neworder.setCreatorId(loggedInID);
        neworder.setProdName(ProductText.getText());
        neworder.setDate(DateText.getText());
        neworder.setAgentId(AgentText.getText());
        neworder.setStatus(StatusText.getText());
        neworder.setNotes(NotesText.getText());
        neworder.setAddress(AddressText.getText());
        CustomerOrdersData.NewOrder(neworder);
        cust.populateTable(); 
    }//GEN-LAST:event_SubmitButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressText;
    private javax.swing.JTextField AgentText;
    private javax.swing.JTextField CreatorIdText;
    private javax.swing.JTextField DateText;
    private javax.swing.JTextField NotesText;
    private javax.swing.JTextField OrderIdText;
    private javax.swing.JTextField ProductText;
    private javax.swing.JTextField StatusText;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel Title_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
