/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import controller.Orderjava;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Order;

/**
 *
 * @author admin
 */
public class Ups_emp extends javax.swing.JFrame {

    /**
     * Creates new form Ups_emp
     */
    private Order selectedorder;
    private ArrayList<Order> orders;
    
    public Ups_emp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        orderstatusLabel = new javax.swing.JLabel();
        orderstatusComboBox = new javax.swing.JComboBox<>();
        orderstatusButton = new javax.swing.JButton();
        orderstatusTextField = new javax.swing.JTextField();
        changestatusLabel = new javax.swing.JLabel();
        orderstatusUpdateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 76, 109));

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ORDERID", "CREATORID", "PRODUCTNAME", "ADDRESS", "PLACEDATE", "AGENTID", "STATUS", "NOTES"
            }
        ));
        jScrollPane1.setViewportView(orderTable);

        orderstatusLabel.setBackground(new java.awt.Color(153, 204, 255));
        orderstatusLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        orderstatusLabel.setText("                                                                      Delivery Agent Portal");

        orderstatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In process", "Out for Delivery", "Delivered", " " }));
        orderstatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderstatusComboBoxActionPerformed(evt);
            }
        });

        orderstatusButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        orderstatusButton.setText("Order Status");
        orderstatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderstatusButtonActionPerformed(evt);
            }
        });

        orderstatusTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderstatusTextFieldActionPerformed(evt);
            }
        });

        changestatusLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        changestatusLabel.setText("Change Status");

        orderstatusUpdateButton.setText("Update");
        orderstatusUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderstatusUpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(changestatusLabel)
                            .addGap(449, 449, 449))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(orderstatusButton)
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(orderstatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(orderstatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(orderstatusUpdateButton)))
                .addContainerGap(142, Short.MAX_VALUE))
            .addComponent(orderstatusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(orderstatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderstatusButton)
                    .addComponent(orderstatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changestatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderstatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(orderstatusUpdateButton)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderstatusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderstatusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderstatusTextFieldActionPerformed

    private void orderstatusUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderstatusUpdateButtonActionPerformed
        // TODO add your handling code here:
        Order neworder = new Order();
 //       neworder.setOrderstatus(orderstatusComboBox.getSelectedItem().toString());
//        newUser.setAge(ageField.getText());

        

        try {
            
            neworder.setOrderstatus(orderstatusComboBox.getSelectedItem().toString());

//insert into db
            Orderjava.editorder(selectedorder, neworder);
            JOptionPane.showMessageDialog(null, "Order Edited Successfully", "Successful Edit", JOptionPane.PLAIN_MESSAGE);
            clearFields();
            populateTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
    }//GEN-LAST:event_orderstatusUpdateButtonActionPerformed

    private void orderstatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderstatusButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = orderTable.getSelectedRow();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Please select an order to edit", "Cannot edit Order", JOptionPane.PLAIN_MESSAGE);
            return;
        }
//        int column = orderTable.getSelectedColumn();
//        int row = orderTable.getSelectedRow();
//        String status = orderTable.getModel().getValueAt(row, column).toString();
//        orderstatusTextField.setText(status);
          selectedorder = orders.get(selectedIndex);
          orderstatusTextField.setText(selectedorder.getOrderstatus());

        
    }//GEN-LAST:event_orderstatusButtonActionPerformed

    private void orderstatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderstatusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderstatusComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ups_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ups_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ups_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ups_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ups_emp().setVisible(true);
            }
        });
    }
    
    public void populateTable() {
        try {
            this.orders = Orderjava.getAllorders();
            DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
            model.setRowCount(0);
            for (Order o : orders) {
                Object[] row = new Object[8];
                row[0] = o.getOrderid();
//                row[0] = u;
                row[1] = o.getCreatorid();
                row[2] = o.getProductname();
                row[3] = o.getAddress();
                row[4] = o.getPlacedate();
                row[5] = o.getAgentid();
                row[6] = o.getOrderstatus();
                row[7] = o.getNotes();
                model.addRow(row);
            }
            clearFields();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void clearFields() {
        orderstatusTextField.setText("");
        selectedorder = null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changestatusLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderTable;
    private javax.swing.JButton orderstatusButton;
    private javax.swing.JComboBox<String> orderstatusComboBox;
    private javax.swing.JLabel orderstatusLabel;
    private javax.swing.JTextField orderstatusTextField;
    private javax.swing.JButton orderstatusUpdateButton;
    // End of variables declaration//GEN-END:variables
}
